import type { BillingPlan, ShopItem } from '@/types/billing';

// Initial pre-configured plans
export const INITIAL_PLANS: BillingPlan[] = [
  {
    id: 'pioneer',
    name: 'Пионер Кольца',
    name_en: 'Ring Pioneer',
    description: 'Базовый премиальный статус для исследователей и строителей колонии.',
    description_en: 'Standard premium tier for Ring explorers and builders.',
    price_rub: 290,
    price_credits: 2500,
    period_days: 30,
    badge_label: 'PIONEER',
    discount_pct: 25,
    color: '#3498db',
    is_active: true,
    is_popular: false,
    display_order: 1,
    perks: [
      'Особый позывной и тактический префикс [PIO]',
      'Приоритетная синхронизация логов CAPI и журнала',
      'Скидка 25% на косметические улучшения в магазине',
      'Эксклюзивный знак отличия Пионера в профиле',
      'Доступ к расширенной телеметрии экспедиции',
    ],
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'elite',
    name: 'Элита Колонии',
    name_en: 'Colonia Elite',
    description: 'Расширенный статус с кастомными темами интерфейса и голографическими рамками.',
    description_en: 'Advanced tier with custom HUD interface themes and holographic avatar frames.',
    price_rub: 590,
    price_credits: 5000,
    period_days: 30,
    badge_label: 'ELITE',
    discount_pct: 50,
    color: '#e67e22',
    is_active: true,
    is_popular: true,
    display_order: 2,
    perks: [
      'Все привилегии уровня «Пионер Кольца»',
      'Голографическая неоновая рамка аватара на выбор',
      'Кастомные HUD-темы оформления интерфейса сайта',
      'Скидка 50% на все товары Премиум-магазина',
      'Приоритет в голосовых каналах эскадрилий',
      'Нагрудный знак ветерана Элиты Колонии',
      'Увеличенный лимит избранных систем в Атласе до 100',
    ],
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'admiral',
    name: 'Флотоводец VIP',
    name_en: 'Fleet Admiral VIP',
    description: 'Высший ранг покровителя проекта с полным доступом ко всем украшениям и VIP-каналам.',
    description_en: 'Highest benefactor tier with full access to all cosmetics and VIP priority.',
    price_rub: 1190,
    price_credits: 10000,
    period_days: 30,
    badge_label: 'VIP ADMIRAL',
    discount_pct: 75,
    color: '#9b59b6',
    is_active: true,
    is_popular: false,
    display_order: 3,
    perks: [
      'Полный безлимитный доступ ко всем модулям платформы',
      'Анимированные эффекты хроматического свечения ника',
      'Все легендарные голографические рамки аватаров',
      'Скидка 75% в магазине косметики + доступ к VIP-эксклюзивам',
      'VIP-статус в технической поддержке с ускоренным ответом',
      'Именная золотая запись в реестре Основателей Кольца',
      'Личный золотой штандарт Флотоводца с орлиными крыльями',
      'Возможность закреплять сообщения в общем чате',
    ],
    created_at: '2026-01-15T00:00:00Z',
  },
];

// Initial pre-configured shop cosmetics
export const INITIAL_SHOP_ITEMS: ShopItem[] = [
  // ── Frames ──
  {
    id: 'frame-singularity',
    category: 'frame',
    title: 'Квантовая Сингулярность',
    title_en: 'Quantum Singularity',
    description: 'Вращающееся гравитационное кольцо аккреционного диска с фиолетовым свечением искривленного пространства.',
    description_en: 'Rotating gravitational accretion disk with violet curved space glow.',
    price_credits: 3500,
    price_rub: 450,
    rarity: 'legendary',
    requires_subscription: null,
    subscriber_discount_pct: 35,
    preview_data: {
      color: '#a855f7',
      accentColor: '#3b82f6',
      glowColor: 'rgba(168, 85, 247, 0.65)',
      frameStyle: 'singularity',
      borderWidth: 3,
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'frame-vanguard',
    category: 'frame',
    title: 'Авангард Колонии',
    title_en: 'Colonia Vanguard',
    description: 'Тактическая бронированная рамка с угловыми оптическими визирами и янтарной телеметрией.',
    description_en: 'Tactical armored frame with corner optical brackets and amber telemetry.',
    price_credits: 2200,
    price_rub: 290,
    rarity: 'epic',
    requires_subscription: null,
    subscriber_discount_pct: 25,
    preview_data: {
      color: '#e67e22',
      accentColor: '#f39c12',
      glowColor: 'rgba(230, 126, 34, 0.55)',
      frameStyle: 'vanguard',
      borderWidth: 2,
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-05T00:00:00Z',
  },
  {
    id: 'frame-subzero',
    category: 'frame',
    title: 'Ледяной Импульс',
    title_en: 'Sub-Zero Pulse',
    description: 'Криогенный гексагональный силовой щит с бегущей волной неонового циана.',
    description_en: 'Cryogenic hexagonal power shield with running neon cyan wave.',
    price_credits: 1500,
    price_rub: 190,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#06b6d4',
      accentColor: '#38bdf8',
      glowColor: 'rgba(6, 182, 212, 0.6)',
      frameStyle: 'subzero',
      borderWidth: 2,
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'frame-solar',
    category: 'frame',
    title: 'Вспышка Сверхновой',
    title_en: 'Solar Flare',
    description: 'Плазменная корона звезды O-класса с пульсирующими выбросами солнечного протуберанца.',
    description_en: 'O-class star plasma corona with pulsing solar prominences.',
    price_credits: 2400,
    price_rub: 320,
    rarity: 'epic',
    requires_subscription: 'elite',
    subscriber_discount_pct: 50,
    preview_data: {
      color: '#f97316',
      accentColor: '#eab308',
      glowColor: 'rgba(249, 115, 22, 0.7)',
      frameStyle: 'solar',
      borderWidth: 3,
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'frame-stealth',
    category: 'frame',
    title: 'Фантом Бездны',
    title_en: 'Stealth Phantom',
    description: 'Композитное углеродное покрытие с матовым черным профилем и приглушенным рубиновым сканером.',
    description_en: 'Composite carbon coating with matte black profile and ruby scanner.',
    price_credits: 1600,
    price_rub: 210,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#ef4444',
      accentColor: '#1e2022',
      glowColor: 'rgba(239, 68, 68, 0.45)',
      frameStyle: 'stealth',
      borderWidth: 2,
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-20T00:00:00Z',
  },

  // ── Badges ──
  {
    id: 'badge-founder',
    category: 'badge',
    title: 'Орден Основателя Кольца',
    title_en: 'Ring Founder Crest',
    description: 'Золотой двуглавый звездный орел с пульсаром в центре. Знак высшего признания заслуг перед экспедицией.',
    description_en: 'Golden double-headed star eagle with central pulsar. Symbol of highest honor.',
    price_credits: 2800,
    price_rub: 390,
    rarity: 'legendary',
    requires_subscription: 'admiral',
    subscriber_discount_pct: 50,
    preview_data: {
      color: '#fbbf24',
      icon: 'crown',
      badgeSvg: 'founder_wings',
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'badge-explorer',
    category: 'badge',
    title: 'Звездный Первопроходец',
    title_en: 'Deep Space Pioneer',
    description: 'Навигационный астролябический компас с указанием на координаты центра Галактики.',
    description_en: 'Astrolabe navigation compass pointing towards Sagittarius A*.',
    price_credits: 1200,
    price_rub: 150,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 15,
    preview_data: {
      color: '#38bdf8',
      icon: 'compass',
      badgeSvg: 'explorer_compass',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-08T00:00:00Z',
  },
  {
    id: 'badge-titan',
    category: 'badge',
    title: 'Покоритель Титанов',
    title_en: 'Titan Slayer',
    description: 'Биолюминесцентная кислотно-изумрудная метка победы над Таргоидскими материнскими кораблями.',
    description_en: 'Bioluminescent emerald mark of victory against Thargoid Titan motherships.',
    price_credits: 2000,
    price_rub: 260,
    rarity: 'epic',
    requires_subscription: null,
    subscriber_discount_pct: 25,
    preview_data: {
      color: '#10b981',
      icon: 'sword',
      badgeSvg: 'titan_breaker',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-12T00:00:00Z',
  },
  {
    id: 'badge-carrier',
    category: 'badge',
    title: 'Владелец Флагмана',
    title_en: 'Fleet Carrier Sovereign',
    description: 'Тяжелый алмазный адмиралтейский шеврон командующего флотом мегакораблей.',
    description_en: 'Heavy diamond admiralty chevron of a megaship carrier fleet commander.',
    price_credits: 2100,
    price_rub: 280,
    rarity: 'epic',
    requires_subscription: 'pioneer',
    subscriber_discount_pct: 30,
    preview_data: {
      color: '#60a5fa',
      icon: 'anchor',
      badgeSvg: 'carrier_diamond',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-18T00:00:00Z',
  },
  {
    id: 'badge-mining',
    category: 'badge',
    title: 'Мастер Глубинного Бурения',
    title_en: 'Core Mining Supreme',
    description: 'Сияющий кристалл редких минералов кольца, расколотый сейсмическим зарядом.',
    description_en: 'Gleaming ring core mineral crystal cracked by seismic charges.',
    price_credits: 800,
    price_rub: 99,
    rarity: 'common',
    requires_subscription: null,
    subscriber_discount_pct: 10,
    preview_data: {
      color: '#a3e635',
      icon: 'diamond',
      badgeSvg: 'mining_drill',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-22T00:00:00Z',
  },

  // ── HUD Skins ──
  {
    id: 'skin-amber',
    category: 'skin',
    title: 'Колониальный Закат',
    title_en: 'Colonia Sunset',
    description: 'Теплая янтарно-медная палитра приборов, создающая атмосферу уюта далеких колониальных станций.',
    description_en: 'Warm amber-copper HUD palette reminiscent of deep Colonia space outposts.',
    price_credits: 900,
    price_rub: 120,
    rarity: 'common',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#f59e0b',
      accentColor: '#d97706',
      hudSkinClass: 'skin-colonia-amber',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'skin-cyber',
    category: 'skin',
    title: 'Киберпанк 3309',
    title_en: 'Cyberpunk 3309',
    description: 'Высококонтрастный футуристичный стиль с неоновым цианом и пульсирующей неоновой маджентой.',
    description_en: 'High-contrast futuristic HUD skin with cyber cyan and pulsing neon magenta.',
    price_credits: 2500,
    price_rub: 330,
    rarity: 'epic',
    requires_subscription: 'elite',
    subscriber_discount_pct: 50,
    preview_data: {
      color: '#ec4899',
      accentColor: '#06b6d4',
      hudSkinClass: 'skin-cyberpunk-3309',
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-05T00:00:00Z',
  },
  {
    id: 'skin-void',
    category: 'skin',
    title: 'Холодный Космос',
    title_en: 'Void Navigator',
    description: 'Глубокий флотский ультрамарин с серебряной подсветкой для снижения нагрузки на зрение в дальних перелетах.',
    description_en: 'Deep naval ultramarine with silver telemetry for low-fatigue long-range jumping.',
    price_credits: 1400,
    price_rub: 180,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#3b82f6',
      accentColor: '#93c5fd',
      hudSkinClass: 'skin-void-navigator',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-14T00:00:00Z',
  },
  {
    id: 'skin-imperial',
    category: 'skin',
    title: 'Имперское Золото',
    title_en: 'Imperial Sovereign Gold',
    description: 'Аристократическая тема в стилистике кораблей Гутмайя — чистый обсидиан и полированное имперское золото.',
    description_en: 'Aristocratic Gutamaya-inspired theme with pure obsidian and polished imperial gold.',
    price_credits: 3200,
    price_rub: 420,
    rarity: 'legendary',
    requires_subscription: 'admiral',
    subscriber_discount_pct: 60,
    preview_data: {
      color: '#eab308',
      accentColor: '#fef08a',
      hudSkinClass: 'skin-imperial-gold',
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'skin-emerald',
    category: 'skin',
    title: 'Изумрудный Стан',
    title_en: 'Emerald Outpost',
    description: 'Милитаристский изумрудный интерфейс орбитальной обороны с повышенной четкостью шрифтов.',
    description_en: 'Tactical military emerald orbital defence HUD with crisp high-clarity typography.',
    price_credits: 1500,
    price_rub: 190,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#10b981',
      accentColor: '#34d399',
      hudSkinClass: 'skin-emerald-outpost',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-24T00:00:00Z',
  },

  // ── Callsign Glow ──
  {
    id: 'glow-hyperspace',
    category: 'glow',
    title: 'Призматический Гиперпрыжок',
    title_en: 'Hyperdrive Prismatic Shimmer',
    description: 'Хроматический спектральный перелив имени пилота с эффектом искривления червоточины Witchspace.',
    description_en: 'Chromatic spectral shimmer effect mimicking Witchspace corridor entry.',
    price_credits: 2900,
    price_rub: 380,
    rarity: 'legendary',
    requires_subscription: 'elite',
    subscriber_discount_pct: 50,
    preview_data: {
      color: '#8b5cf6',
      accentColor: '#ec4899',
      gradient: 'linear-gradient(90deg, #ec4899, #8b5cf6, #06b6d4, #ec4899)',
      glowColor: '0 0 12px rgba(139, 92, 246, 0.75)',
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-03T00:00:00Z',
  },
  {
    id: 'glow-neutron',
    category: 'glow',
    title: 'Свечение Нейтронной Струи',
    title_en: 'Neutron Jet Beam',
    description: 'Ослепительно яркий конический луч нейтронной звезды с белым электромагнитным ядром.',
    description_en: 'Dazzling conical relativistic jet glow with bright electromagnetic core.',
    price_credits: 2100,
    price_rub: 270,
    rarity: 'epic',
    requires_subscription: null,
    subscriber_discount_pct: 25,
    preview_data: {
      color: '#38bdf8',
      accentColor: '#ffffff',
      gradient: 'linear-gradient(90deg, #38bdf8, #e0f2fe, #38bdf8)',
      glowColor: '0 0 14px rgba(56, 189, 248, 0.85)',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-11T00:00:00Z',
  },
  {
    id: 'glow-solar',
    category: 'glow',
    title: 'Солнечная Радиация',
    title_en: 'Solar Radiation Halo',
    description: 'Мягкое теплое золотисто-янтарное гало с переливом цвета расплавленного золота.',
    description_en: 'Soft warm golden-amber halo radiating molten gold shades.',
    price_credits: 1300,
    price_rub: 160,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#f59e0b',
      accentColor: '#fbbf24',
      gradient: 'linear-gradient(90deg, #f59e0b, #fef08a, #f59e0b)',
      glowColor: '0 0 10px rgba(245, 158, 11, 0.65)',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-16T00:00:00Z',
  },
  {
    id: 'glow-voidpulse',
    category: 'glow',
    title: 'Тень Сингулярности',
    title_en: 'Void Singularity Shadow',
    description: 'Таинственная пульсирующая фиолетово-черная аура с эффектом гравитационного линзирования текста.',
    description_en: 'Mysterious pulsing violet-black aura with gravitational text lensing.',
    price_credits: 1400,
    price_rub: 170,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#9333ea',
      accentColor: '#c084fc',
      gradient: 'linear-gradient(90deg, #9333ea, #e9d5ff, #9333ea)',
      glowColor: '0 0 12px rgba(147, 51, 234, 0.7)',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-21T00:00:00Z',
  },

  // ── Titles ──
  {
    id: 'title-architect',
    category: 'title',
    title: 'Архитектор Нового Рубежа',
    title_en: 'Architect of the New Frontier',
    description: 'Высшее почетное звание для лидеров колонизационных проектов и строителей мегаструктур.',
    description_en: 'Honorary title for colonization project leaders and megastructure builders.',
    price_credits: 1800,
    price_rub: 240,
    rarity: 'epic',
    requires_subscription: 'pioneer',
    subscriber_discount_pct: 30,
    preview_data: {
      color: '#f97316',
      subTitle: 'ARCHITECT OF THE NEW FRONTIER',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-04T00:00:00Z',
  },
  {
    id: 'title-trailblazer',
    category: 'title',
    title: 'Первопроходец Бездны',
    title_en: 'Void Trailblazer',
    description: 'Легендарный титул командиров, преодолевших тысячи световых лет в неизвестные сектора кольца.',
    description_en: 'Legendary title for commanders navigating untamed deep space sectors.',
    price_credits: 2600,
    price_rub: 350,
    rarity: 'legendary',
    requires_subscription: 'elite',
    subscriber_discount_pct: 40,
    preview_data: {
      color: '#a855f7',
      subTitle: 'VOID TRAILBLAZER',
    },
    is_active: true,
    is_featured: true,
    sales_count: 0,
    created_at: '2026-02-09T00:00:00Z',
  },
  {
    id: 'title-jaques',
    category: 'title',
    title: 'Легенда Жак-Стейшн',
    title_en: 'Jaques Station Legend',
    description: 'Звание ветерана исторического маршрута из Пузыря в Колонию.',
    description_en: 'Title bestowed upon veterans of the historic Sol-to-Colonia highway.',
    price_credits: 1200,
    price_rub: 150,
    rarity: 'rare',
    requires_subscription: null,
    subscriber_discount_pct: 20,
    preview_data: {
      color: '#38bdf8',
      subTitle: 'JAQUES STATION LEGEND',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 'title-marshal',
    category: 'title',
    title: 'Маршал Звездного Пути',
    title_en: 'Starway Marshal',
    description: 'Почетный титул организаторов и защитников колонизационных конвоев.',
    description_en: 'Honorary title for organizers and protectors of colonial supply convoys.',
    price_credits: 3000,
    price_rub: 400,
    rarity: 'legendary',
    requires_subscription: 'admiral',
    subscriber_discount_pct: 50,
    preview_data: {
      color: '#eab308',
      subTitle: 'STARWAY MARSHAL',
    },
    is_active: true,
    is_featured: false,
    sales_count: 0,
    created_at: '2026-02-23T00:00:00Z',
  },
];
