/**
 * Каталог построек колонизации (Elite Dangerous: Trailblazers / Operations).
 *
 * Файл-данные: для каждого типа постройки — класс, тир, расположение, посадочная
 * площадка, стоимость в очках системы (needs/gives), требования-предшественники,
 * вклад в оценку системы и эффекты, а также полный список товаров и их тоннаж.
 *
 * Числа — игровые данные Elite Dangerous (стоимости построек и правила очков
 * тиров), которые сообщество собирает по сканам стройплощадок; сверялись с
 * публичными источниками (Raven Colonial / ED Wiki / форум Frontier). Код вокруг
 * данных — собственный: `src/lib/architect/planner.ts` и тесты в
 * `scripts/tests/system-architect.test.mjs`.
 *
 * Правки вносите через `CATALOGUE_VERSION`: план-черновик хранит версию, и
 * загрузчик честно говорит, что каталог изменился.
 */

import type {
  ArchitectBuildClass,
  ArchitectInstallation,
  ArchitectPadSize,
  ArchitectPreReq,
  SystemEconomy,
} from './types.ts';

/** Версия набора данных: bump при изменении стоимостей или правил. */
export const CATALOGUE_VERSION = 3;

/** Русские названия товаров (как в русской локализации игры). */
export const COMMODITY_LABELS_RU: Record<string, string> = {
  advancedcatalysers: 'Усовершенствованные катализаторы',
  agriculturalmedicines: 'Агромедикаменты',
  aluminium: 'Алюминий',
  animalmeat: 'Мясо животных',
  autofabricators: 'Автофабрикаторы',
  basicmedicines: 'Базовые медикаменты',
  battleweapons: 'Боевое оружие',
  beer: 'Пиво',
  bioreducinglichen: 'Биоредуцирующий лишайник',
  biowaste: 'Биоотходы',
  buildingfabricators: 'Строительные фабрикаторы',
  ceramiccomposites: 'Керамические композиты',
  cmmcomposite: 'CMM-композит',
  coffee: 'Кофе',
  combatstabilisers: 'Боевые стабилизаторы',
  computercomponents: 'Компьютерные компоненты',
  copper: 'Медь',
  cropharvesters: 'Уборщики урожая',
  emergencypowercells: 'Аварийные энергоячейки',
  evacuationshelter: 'Эвакуационное убежище',
  fish: 'Рыба',
  foodcartridges: 'Пищевые картриджи',
  fruitandvegetables: 'Фрукты и овощи',
  geologicalequipment: 'Геологическое оборудование',
  grain: 'Зерно',
  hazardousenvironmentsuits: 'Костюмы для опасных сред',
  heliostaticfurnaces: 'Гелиостатические печи',
  insulatingmembrane: 'Изоляционная мембрана',
  liquidoxygen: 'Жидкий кислород',
  liquor: 'Ликёр',
  medicaldiagnosticequipment: 'Мед. диагностическое оборудование',
  microcontrollers: 'Микроконтроллеры',
  militarygradefabrics: 'Ткани военного класса',
  mineralextractors: 'Минеральные экстракторы',
  mutomimager: 'Муто-имиджер',
  nonlethalweapons: 'Нелетальное оружие',
  pesticides: 'Пестициды',
  polymers: 'Полимеры',
  powergenerators: 'Генераторы энергии',
  reactivearmour: 'Реактивная броня',
  resonatingseparators: 'Резонирующие сепараторы',
  robotics: 'Роботы',
  semiconductors: 'Полупроводники',
  steel: 'Сталь',
  structuralregulators: 'Структурные регуляторы',
  superconductors: 'Сверхпроводники',
  surfacestabilisers: 'Поверхностные стабилизаторы',
  survivalequipment: 'Спасательное снаряжение',
  tea: 'Чай',
  terrainenrichmentsystems: 'Системы обогащения почвы',
  thermalcoolingunits: 'Термальные охладители',
  titanium: 'Титан',
  water: 'Вода',
  waterpurifiers: 'Водоочистители',
  wine: 'Вино',
};

/** Русские названия типов экономики системы. */
export const ECONOMY_LABELS_RU: Record<SystemEconomy, string> = {
  colony: 'колония',
  extraction: 'добыча',
  industrial: 'промышленность',
  hightech: 'высокие технологии',
  military: 'военные',
  agriculture: 'сельское хозяйство',
  tourism: 'туризм',
  service: 'услуги',
  refinery: 'переработка',
  contraband: 'контрабанда',
  none: '—',
};

/** Русские названия классов построек. */
export const BUILD_CLASS_LABELS_RU: Record<ArchitectBuildClass, string> = {
  starport: 'звёздный порт',
  outpost: 'аванпост',
  installation: 'установка',
  settlement: 'поселение',
  hub: 'хаб',
  unknown: 'неизвестно',
};

/** Русские подписи размеров посадочной площадки. */
export const PAD_LABELS_RU: Record<ArchitectPadSize, string> = {
  none: 'нет',
  small: 'малая',
  medium: 'средняя',
  large: 'большая',
};

/**
 * Цепочки предшественников: постройку нельзя запланировать, пока в системе нет
 * хотя бы одной постройки из списка.
 */
export const PRE_REQS: Record<ArchitectPreReq, { label: string; buildTypes: string[] }> = {
  satellite: { label: 'спутник', buildTypes: ['hermes'] },
  comms: { label: 'станция связи', buildTypes: ['pistis'] },
  relay: { label: 'ретранслятор', buildTypes: ['enodia'] },
  installationAgr: { label: 'космическая ферма', buildTypes: ['demeter'] },
  installationMil: { label: 'военная установка', buildTypes: ['vacuna'] },
  outpostMining: { label: 'добывающая установка', buildTypes: ['euthenia'] },
  settlementAgr: { label: 'сельхозпоселение', buildTypes: ['consus', 'picumnus', 'ceres'] },
  settlementBio: { label: 'хайтек-поселение', buildTypes: ['pheobe', 'asteria', 'chronos'] },
  settlementTourist: { label: 'турпоселение', buildTypes: ['aergia', 'comus', 'fufluns'] },
  settlementMilitary: { label: 'военное поселение', buildTypes: ['ioke', 'bellona', 'minerva'] },
  settlementExtraction: { label: 'добывающее поселение', buildTypes: ['ourea', 'mantus', 'erebus'] },
};

/**
 * Что система «открывает» после постройки определённых объектов: набор
 * дополнительных сервисов, которые можно честно обещать пилотам.
 */
export const SYSTEM_UNLOCKS: { id: string; label: string; buildTypes: string[] }[] = [
  { id: 'tourist-settlement', label: 'Турпоселения (нужен спутник)', buildTypes: ['hermes'] },
  { id: 'tourist-installation', label: 'Туристические установки (нужно турпоселение)', buildTypes: ['aergia', 'comus', 'fufluns'] },
  { id: 'scientific-installation', label: 'Исследовательские станции (нужно хайтек-поселение)', buildTypes: ['pheobe', 'asteria', 'chronos'] },
  { id: 'military-installation', label: 'Военные установки (нужно военное поселение)', buildTypes: ['ioke', 'bellona', 'minerva'] },
  { id: 'military-hub', label: 'Военный хаб (нужна военная установка)', buildTypes: ['vacuna'] },
  { id: 'civilian-hub', label: 'Гражданский хаб (нужно сельхозпоселение)', buildTypes: ['consus', 'picumnus', 'ceres'] },
  { id: 'exploration-hub', label: 'Исследовательский хаб (нужна станция связи)', buildTypes: ['pistis'] },
  { id: 'outpost-hub', label: 'Аванпост-хаб (нужна космическая ферма)', buildTypes: ['demeter'] },
  { id: 'industrial-hub', label: 'Индустриальный хаб (нужна добывающая установка)', buildTypes: ['euthenia'] },
  { id: 'extraction-hub', label: 'Добывающий хаб (нужно добывающее поселение)', buildTypes: ['ourea', 'mantus', 'erebus'] },
  { id: 'shipyard', label: 'Верфь у наземного порта T1 (нужен индустриальный хаб или военная установка)', buildTypes: ['molae', 'vacuna'] },
  { id: 'outfitting', label: 'Снаряжение у аванпостов (нужен хайтек-хаб или военная установка)', buildTypes: ['janus', 'vacuna'] },
  { id: 'vista-genomics', label: 'Vista Genomics (нужна мед. установка или научный хаб)', buildTypes: ['asclepius', 'athena'] },
  { id: 'universal-cartographics', label: 'Universal Cartographics (нужна исследовательская станция или исследовательский хаб)', buildTypes: ['astraeus', 'tellus'] },
  { id: 'market-outposts', label: 'Рынок у пиратских/научных/военных аванпостов (нужен бар, тур. установка или аванпост-хаб)', buildTypes: ['dionysus', 'hedone', 'io'] },
  { id: 'crew-lounge', label: 'Комната экипажа у портов T1 (нужен космический бар)', buildTypes: ['dionysus'] },
];

/** Все постройки каталога. Порядок — орбитальные порты, аванпосты, установки, наземные, поселения, хабы. */
export const INSTALLATIONS: ArchitectInstallation[] = [
  {
    id: 'no_truss',
    nameRu: 'Кориолис (звёздный порт)',
    nameEn: 'Coriolis Starport',
    group: 'Coriolis',
    buildClass: 'starport',
    tier: 2,
    location: 'orbital',
    pad: 'large',
    needs: { tier: 2, count: 3 },
    gives: { tier: 3, count: 1 },
    score: 8,
    influence: 'colony',
    effects: { pop: 1, mpop: 1, sec: -2, wealth: 3, tech: 2, sol: 3, dev: 3 },
    haulTons: 53723,
    cargo: {
      aluminium: 10055,
      ceramiccomposites: 1207,
      cmmcomposite: 11261,
      computercomponents: 145,
      copper: 644,
      foodcartridges: 242,
      fruitandvegetables: 145,
      insulatingmembrane: 644,
      liquidoxygen: 3781,
      medicaldiagnosticequipment: 25,
      nonlethalweapons: 25,
      polymers: 1046,
      powergenerators: 65,
      semiconductors: 161,
      steel: 14076,
      superconductors: 282,
      titanium: 8205,
      water: 1609,
      waterpurifiers: 105,
    },
  },
  {
    id: 'asteroid',
    nameRu: 'Астероидная база',
    nameEn: 'Asteroid Base',
    group: 'Asteroid Base',
    buildClass: 'starport',
    tier: 2,
    location: 'orbital',
    pad: 'large',
    needs: { tier: 2, count: 3 },
    gives: { tier: 3, count: 1 },
    score: 8,
    influence: 'extraction',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 5, tech: 3, sol: -4, dev: 7 },
    haulTons: 53723,
    cargo: {
      aluminium: 10055,
      ceramiccomposites: 1207,
      cmmcomposite: 11261,
      computercomponents: 145,
      copper: 644,
      foodcartridges: 242,
      fruitandvegetables: 145,
      insulatingmembrane: 644,
      liquidoxygen: 3781,
      medicaldiagnosticequipment: 25,
      nonlethalweapons: 25,
      polymers: 1046,
      powergenerators: 65,
      semiconductors: 161,
      steel: 14076,
      superconductors: 282,
      titanium: 8205,
      water: 1609,
      waterpurifiers: 105,
    },
  },
  {
    id: 'dodec',
    nameRu: 'Додекаэдр (звёздный порт)',
    nameEn: 'Dodec Starport',
    group: 'Dodec',
    buildClass: 'starport',
    tier: 3,
    location: 'orbital',
    pad: 'large',
    needs: { tier: 3, count: 6 },
    gives: { tier: 0, count: 0 },
    score: 15,
    influence: 'colony',
    effects: { pop: 8, mpop: 4, sec: -4, wealth: 9, tech: 8, sol: 7, dev: 10 },
    haulTons: 236304,
    cargo: {
      aluminium: 45248,
      autofabricators: 314,
      ceramiccomposites: 5432,
      cmmcomposite: 50675,
      computercomponents: 363,
      copper: 2898,
      foodcartridges: 605,
      fruitandvegetables: 363,
      insulatingmembrane: 1610,
      liquidoxygen: 17015,
      medicaldiagnosticequipment: 63,
      nonlethalweapons: 63,
      polymers: 2615,
      powergenerators: 163,
      semiconductors: 403,
      steel: 63342,
      superconductors: 705,
      titanium: 36923,
      water: 7241,
      waterpurifiers: 263,
    },
  },
  {
    id: 'ocellus',
    nameRu: 'Оцеллус (звёздный порт)',
    nameEn: 'Ocellus Starport',
    group: 'Ocellus',
    buildClass: 'starport',
    tier: 3,
    location: 'orbital',
    pad: 'large',
    needs: { tier: 3, count: 6 },
    gives: { tier: 0, count: 0 },
    score: 15,
    influence: 'colony',
    effects: { pop: 5, mpop: 1, sec: -3, wealth: 8, tech: 7, sol: 5, dev: 9 },
    haulTons: 209122,
    cargo: {
      aluminium: 40220,
      ceramiccomposites: 4828,
      cmmcomposite: 45044,
      computercomponents: 290,
      copper: 2576,
      foodcartridges: 484,
      fruitandvegetables: 290,
      insulatingmembrane: 1288,
      liquidoxygen: 15124,
      medicaldiagnosticequipment: 50,
      nonlethalweapons: 50,
      polymers: 2092,
      powergenerators: 130,
      semiconductors: 322,
      steel: 56304,
      superconductors: 564,
      titanium: 32820,
      water: 6436,
      waterpurifiers: 210,
    },
  },
  {
    id: 'apollo',
    nameRu: 'Орбис (звёздный порт)',
    nameEn: 'Orbis Starport',
    group: 'Orbis',
    buildClass: 'starport',
    tier: 3,
    location: 'orbital',
    pad: 'large',
    needs: { tier: 3, count: 6 },
    gives: { tier: 0, count: 0 },
    score: 15,
    influence: 'colony',
    effects: { pop: 5, mpop: 1, sec: -3, wealth: 8, tech: 7, sol: 5, dev: 9 },
    haulTons: 209122,
    cargo: {
      aluminium: 40220,
      ceramiccomposites: 4828,
      cmmcomposite: 45044,
      computercomponents: 290,
      copper: 2576,
      foodcartridges: 484,
      fruitandvegetables: 290,
      insulatingmembrane: 1288,
      liquidoxygen: 15124,
      medicaldiagnosticequipment: 50,
      nonlethalweapons: 50,
      polymers: 2092,
      powergenerators: 130,
      semiconductors: 322,
      steel: 56304,
      superconductors: 564,
      titanium: 32820,
      water: 6436,
      waterpurifiers: 210,
    },
  },
  {
    id: 'plutus',
    nameRu: 'Коммерческий аванпост',
    nameEn: 'Commercial Outpost',
    group: 'Commercial Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'colony',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 3, tech: 0, sol: 5, dev: 0 },
    haulTons: 18473,
    cargo: {
      ceramiccomposites: 497,
      cmmcomposite: 3912,
      computercomponents: 50,
      copper: 218,
      foodcartridges: 94,
      fruitandvegetables: 50,
      insulatingmembrane: 311,
      liquidoxygen: 1553,
      medicaldiagnosticequipment: 13,
      nonlethalweapons: 13,
      polymers: 497,
      powergenerators: 19,
      semiconductors: 56,
      steel: 5588,
      superconductors: 100,
      titanium: 4843,
      water: 621,
      waterpurifiers: 38,
    },
  },
  {
    id: 'vulcan',
    nameRu: 'Промышленный аванпост',
    nameEn: 'Industrial Outpost',
    group: 'Industrial Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 3, sol: 0, dev: 3 },
    haulTons: 18473,
    cargo: {
      ceramiccomposites: 497,
      cmmcomposite: 3912,
      computercomponents: 50,
      copper: 218,
      foodcartridges: 94,
      fruitandvegetables: 50,
      insulatingmembrane: 311,
      liquidoxygen: 1553,
      medicaldiagnosticequipment: 13,
      nonlethalweapons: 13,
      polymers: 497,
      powergenerators: 19,
      semiconductors: 56,
      steel: 5588,
      superconductors: 100,
      titanium: 4843,
      water: 621,
      waterpurifiers: 38,
    },
  },
  {
    id: 'dysnomia',
    nameRu: 'Пиратский аванпост',
    nameEn: 'Pirate Outpost',
    group: 'Criminal Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'service',
    effects: { pop: 1, mpop: 1, sec: -2, wealth: 3, tech: 0, sol: 0, dev: 0 },
    haulTons: 18473,
    cargo: {
      ceramiccomposites: 497,
      cmmcomposite: 3912,
      computercomponents: 50,
      copper: 218,
      foodcartridges: 94,
      fruitandvegetables: 50,
      insulatingmembrane: 311,
      liquidoxygen: 1553,
      medicaldiagnosticequipment: 13,
      nonlethalweapons: 13,
      polymers: 497,
      powergenerators: 19,
      semiconductors: 56,
      steel: 5588,
      superconductors: 100,
      titanium: 4843,
      water: 621,
      waterpurifiers: 38,
    },
  },
  {
    id: 'vesta',
    nameRu: 'Гражданский аванпост',
    nameEn: 'Civilian Outpost',
    group: 'Civilian Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'colony',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 1, tech: 0, sol: 2, dev: 1 },
    haulTons: 18473,
    cargo: {
      ceramiccomposites: 497,
      cmmcomposite: 3912,
      computercomponents: 50,
      copper: 218,
      foodcartridges: 94,
      fruitandvegetables: 50,
      insulatingmembrane: 311,
      liquidoxygen: 1553,
      medicaldiagnosticequipment: 13,
      nonlethalweapons: 13,
      polymers: 497,
      powergenerators: 19,
      semiconductors: 56,
      steel: 5588,
      superconductors: 100,
      titanium: 4843,
      water: 621,
      waterpurifiers: 38,
    },
  },
  {
    id: 'prometheus',
    nameRu: 'Научный аванпост',
    nameEn: 'Scientific Outpost',
    group: 'Scientific Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 3, sol: 0, dev: 0 },
    haulTons: 18473,
    cargo: {
      ceramiccomposites: 497,
      cmmcomposite: 3912,
      computercomponents: 50,
      copper: 218,
      foodcartridges: 94,
      fruitandvegetables: 50,
      insulatingmembrane: 311,
      liquidoxygen: 1553,
      medicaldiagnosticequipment: 13,
      nonlethalweapons: 13,
      polymers: 497,
      powergenerators: 19,
      semiconductors: 56,
      steel: 5588,
      superconductors: 100,
      titanium: 4843,
      water: 621,
      waterpurifiers: 38,
    },
  },
  {
    id: 'nemesis',
    nameRu: 'Военный аванпост',
    nameEn: 'Military Outpost',
    group: 'Military Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'orbital',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'military',
    effects: { pop: 1, mpop: 1, sec: 2, wealth: 0, tech: 0, sol: 0, dev: 0 },
    haulTons: 10080,
    cargo: {
      aluminium: 1317,
      basicmedicines: 24,
      battleweapons: 30,
      ceramiccomposites: 238,
      cmmcomposite: 356,
      combatstabilisers: 48,
      computercomponents: 42,
      copper: 131,
      foodcartridges: 107,
      fruitandvegetables: 48,
      insulatingmembrane: 178,
      liquidoxygen: 1424,
      microcontrollers: 18,
      militarygradefabrics: 36,
      polymers: 416,
      powergenerators: 18,
      reactivearmour: 30,
      steel: 2966,
      titanium: 2373,
      water: 238,
      waterpurifiers: 42,
    },
  },
  {
    id: 'hermes',
    nameRu: 'Спутник',
    nameEn: 'Satellite Installation',
    group: 'Satellite',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'none',
    effects: { pop: 0, mpop: 0, sec: 0, wealth: 1, tech: 0, sol: 2, dev: 1 },
    haulTons: 6721,
    cargo: {
      aluminium: 1322,
      ceramiccomposites: 85,
      computercomponents: 22,
      copper: 85,
      foodcartridges: 26,
      fruitandvegetables: 9,
      insulatingmembrane: 106,
      liquidoxygen: 678,
      microcontrollers: 13,
      polymers: 170,
      powergenerators: 9,
      semiconductors: 34,
      steel: 2542,
      superconductors: 60,
      titanium: 1525,
      water: 22,
      waterpurifiers: 13,
    },
  },
  {
    id: 'pistis',
    nameRu: 'Станция связи',
    nameEn: 'Comms Installation',
    group: 'Communication Station',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'none',
    effects: { pop: 0, mpop: 0, sec: 1, wealth: 0, tech: 3, sol: 0, dev: 0 },
    haulTons: 6721,
    cargo: {
      aluminium: 1322,
      ceramiccomposites: 85,
      computercomponents: 22,
      copper: 85,
      foodcartridges: 26,
      fruitandvegetables: 9,
      insulatingmembrane: 106,
      liquidoxygen: 678,
      microcontrollers: 13,
      polymers: 170,
      powergenerators: 9,
      semiconductors: 34,
      steel: 2542,
      superconductors: 60,
      titanium: 1525,
      water: 22,
      waterpurifiers: 13,
    },
  },
  {
    id: 'demeter',
    nameRu: 'Космическая ферма',
    nameEn: 'Agricultural Installation',
    group: 'Space Farm',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'agriculture',
    effects: { pop: 0, mpop: 0, sec: 0, wealth: 0, tech: 0, sol: 5, dev: 1 },
    haulTons: 6722,
    cargo: {
      agriculturalmedicines: 115,
      aluminium: 842,
      biowaste: 153,
      ceramiccomposites: 77,
      computercomponents: 12,
      copper: 46,
      cropharvesters: 77,
      foodcartridges: 46,
      fruitandvegetables: 69,
      grain: 92,
      insulatingmembrane: 192,
      liquidoxygen: 1071,
      pesticides: 123,
      polymers: 230,
      powergenerators: 8,
      steel: 1912,
      titanium: 1453,
      water: 173,
      waterpurifiers: 31,
    },
  },
  {
    id: 'apate',
    nameRu: 'Пиратская база',
    nameEn: 'Pirate Installation',
    group: 'Pirate Base',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'service',
    effects: { pop: 0, mpop: 0, sec: -4, wealth: 4, tech: 0, sol: 0, dev: 0 },
    haulTons: 6721,
    cargo: {
      aluminium: 1233,
      battleweapons: 23,
      beer: 380,
      ceramiccomposites: 95,
      computercomponents: 19,
      copper: 57,
      foodcartridges: 61,
      fruitandvegetables: 16,
      insulatingmembrane: 95,
      liquidoxygen: 911,
      liquor: 228,
      polymers: 190,
      powergenerators: 8,
      reactivearmour: 23,
      steel: 1707,
      titanium: 1594,
      water: 65,
      waterpurifiers: 16,
    },
  },
  {
    id: 'euthenia',
    nameRu: 'Добывающая установка',
    nameEn: 'Industrial Installation',
    group: 'Mining Outpost',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'extraction',
    effects: { pop: 0, mpop: 0, sec: 0, wealth: 4, tech: 0, sol: -2, dev: 0 },
    haulTons: 6723,
    cargo: {
      aluminium: 921,
      bioreducinglichen: 172,
      ceramiccomposites: 86,
      computercomponents: 13,
      copper: 52,
      foodcartridges: 52,
      fruitandvegetables: 18,
      geologicalequipment: 26,
      hazardousenvironmentsuits: 13,
      insulatingmembrane: 129,
      liquidoxygen: 1028,
      mutomimager: 43,
      polymers: 215,
      powergenerators: 9,
      resonatingseparators: 22,
      robotics: 60,
      steel: 2141,
      titanium: 1628,
      water: 73,
      waterpurifiers: 22,
    },
  },
  {
    id: 'enodia',
    nameRu: 'Ретранслятор',
    nameEn: 'Relay Installation',
    group: 'Relay Station',
    buildClass: 'installation',
    tier: 1,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 3,
    influence: 'hightech',
    effects: { pop: 0, mpop: 0, sec: 1, wealth: 0, tech: 0, sol: 0, dev: 1 },
    haulTons: 6721,
    cargo: {
      aluminium: 1033,
      ceramiccomposites: 98,
      computercomponents: 25,
      copper: 88,
      foodcartridges: 30,
      fruitandvegetables: 10,
      insulatingmembrane: 122,
      liquidoxygen: 780,
      polymers: 195,
      powergenerators: 10,
      semiconductors: 39,
      steel: 2437,
      superconductors: 59,
      titanium: 1755,
      water: 25,
      waterpurifiers: 15,
    },
  },
  {
    id: 'vacuna',
    nameRu: 'Военная установка',
    nameEn: 'Military Installation',
    group: 'Military',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'settlementMilitary',
    score: 4,
    influence: 'military',
    effects: { pop: 0, mpop: 0, sec: 7, wealth: 0, tech: 0, sol: 0, dev: 0 },
    haulTons: 10080,
    cargo: {
      aluminium: 1317,
      basicmedicines: 24,
      battleweapons: 30,
      ceramiccomposites: 238,
      cmmcomposite: 356,
      combatstabilisers: 48,
      computercomponents: 42,
      copper: 131,
      foodcartridges: 107,
      fruitandvegetables: 48,
      insulatingmembrane: 178,
      liquidoxygen: 1424,
      microcontrollers: 18,
      militarygradefabrics: 36,
      polymers: 416,
      powergenerators: 18,
      reactivearmour: 30,
      steel: 2966,
      titanium: 2373,
      water: 238,
      waterpurifiers: 42,
    },
  },
  {
    id: 'dicaeosyne',
    nameRu: 'Охранная станция',
    nameEn: 'Security Installation',
    group: 'Security Station',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'relay',
    score: 3,
    influence: 'military',
    effects: { pop: 0, mpop: 0, sec: 9, wealth: 0, tech: 0, sol: 3, dev: 3 },
    haulTons: 10082,
    cargo: {
      aluminium: 1774,
      battleweapons: 19,
      ceramiccomposites: 122,
      combatstabilisers: 25,
      computercomponents: 31,
      copper: 122,
      foodcartridges: 37,
      fruitandvegetables: 13,
      insulatingmembrane: 183,
      liquidoxygen: 1458,
      militarygradefabrics: 19,
      nonlethalweapons: 19,
      polymers: 243,
      powergenerators: 13,
      steel: 3645,
      titanium: 2309,
      water: 31,
      waterpurifiers: 19,
    },
  },
  {
    id: 'harmonia',
    nameRu: 'Правительственная установка',
    nameEn: 'Government Installation',
    group: 'Government',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 3,
    influence: 'none',
    effects: { pop: 0, mpop: 0, sec: 2, wealth: 0, tech: 0, sol: 7, dev: 3 },
    haulTons: 10077,
    cargo: {
      aluminium: 1959,
      ceramiccomposites: 154,
      computercomponents: 13,
      copper: 93,
      foodcartridges: 93,
      fruitandvegetables: 37,
      insulatingmembrane: 247,
      liquidoxygen: 1479,
      nonlethalweapons: 13,
      polymers: 370,
      powergenerators: 13,
      steel: 3080,
      titanium: 2341,
      water: 154,
      waterpurifiers: 31,
    },
  },
  {
    id: 'asclepius',
    nameRu: 'Медицинская установка',
    nameEn: 'Medical Installation',
    group: 'Medical',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 4,
    influence: 'hightech',
    effects: { pop: 0, mpop: 0, sec: 0, wealth: 0, tech: 3, sol: 5, dev: 0 },
    haulTons: 10081,
    cargo: {
      aluminium: 1357,
      basicmedicines: 50,
      ceramiccomposites: 155,
      combatstabilisers: 19,
      computercomponents: 31,
      copper: 112,
      foodcartridges: 75,
      fruitandvegetables: 50,
      hazardousenvironmentsuits: 25,
      insulatingmembrane: 309,
      liquidoxygen: 1727,
      medicaldiagnosticequipment: 99,
      polymers: 371,
      powergenerators: 19,
      steel: 3084,
      titanium: 2282,
      water: 278,
      waterpurifiers: 38,
    },
  },
  {
    id: 'astraeus',
    nameRu: 'Исследовательская станция',
    nameEn: 'Scientific Installation',
    group: 'Research Station',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'settlementBio',
    score: 4,
    influence: 'hightech',
    effects: { pop: 0, mpop: 0, sec: 0, wealth: 0, tech: 8, sol: 0, dev: 3 },
    haulTons: 10083,
    cargo: {
      advancedcatalysers: 44,
      aluminium: 1380,
      basicmedicines: 13,
      ceramiccomposites: 157,
      computercomponents: 38,
      copper: 126,
      foodcartridges: 76,
      fruitandvegetables: 26,
      geologicalequipment: 26,
      hazardousenvironmentsuits: 32,
      insulatingmembrane: 314,
      liquidoxygen: 1506,
      medicaldiagnosticequipment: 51,
      microcontrollers: 13,
      mutomimager: 38,
      polymers: 377,
      powergenerators: 13,
      semiconductors: 51,
      steel: 3136,
      superconductors: 88,
      titanium: 2383,
      water: 157,
      waterpurifiers: 38,
    },
  },
  {
    id: 'hedone',
    nameRu: 'Туристическая установка',
    nameEn: 'Tourist Installation',
    group: 'Tourist',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'settlementTourist',
    score: 3,
    influence: 'tourism',
    effects: { pop: 0, mpop: 0, sec: -3, wealth: 6, tech: 0, sol: 0, dev: 3 },
    haulTons: 10078,
    cargo: {
      aluminium: 1269,
      animalmeat: 78,
      beer: 389,
      ceramiccomposites: 130,
      coffee: 130,
      computercomponents: 13,
      copper: 78,
      fish: 39,
      fruitandvegetables: 65,
      insulatingmembrane: 259,
      liquidoxygen: 1813,
      liquor: 195,
      polymers: 324,
      powergenerators: 13,
      steel: 2589,
      tea: 259,
      titanium: 1813,
      water: 324,
      waterpurifiers: 39,
      wine: 259,
    },
  },
  {
    id: 'dionysus',
    nameRu: 'Космический бар',
    nameEn: 'Space Bar',
    group: 'Bar',
    buildClass: 'installation',
    tier: 2,
    location: 'orbital',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 4,
    influence: 'tourism',
    effects: { pop: 0, mpop: 0, sec: -2, wealth: 3, tech: 0, sol: 3, dev: 0 },
    haulTons: 10085,
    cargo: {
      aluminium: 1217,
      animalmeat: 38,
      beer: 497,
      ceramiccomposites: 125,
      coffee: 63,
      computercomponents: 13,
      copper: 75,
      fish: 19,
      fruitandvegetables: 38,
      insulatingmembrane: 249,
      liquidoxygen: 1738,
      liquor: 311,
      polymers: 311,
      powergenerators: 13,
      steel: 2483,
      tea: 187,
      titanium: 1738,
      water: 311,
      waterpurifiers: 38,
      wine: 621,
    },
  },
  {
    id: 'hestia',
    nameRu: 'Гражданское поселение',
    nameEn: 'Civilian Settlement',
    group: 'Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 4,
    influence: 'colony',
    effects: { pop: 2, mpop: 1, sec: -2, wealth: 0, tech: 0, sol: 3, dev: 0 },
    haulTons: 36829,
    cargo: {
      aluminium: 7047,
      buildingfabricators: 407,
      ceramiccomposites: 814,
      cmmcomposite: 6776,
      computercomponents: 102,
      copper: 407,
      emergencypowercells: 68,
      evacuationshelter: 204,
      foodcartridges: 136,
      fruitandvegetables: 95,
      liquidoxygen: 2372,
      medicaldiagnosticequipment: 48,
      nonlethalweapons: 34,
      polymers: 678,
      powergenerators: 68,
      semiconductors: 102,
      steel: 10164,
      structuralregulators: 678,
      superconductors: 136,
      surfacestabilisers: 610,
      survivalequipment: 55,
      terrainenrichmentsystems: 68,
      titanium: 5760,
    },
  },
  {
    id: 'hephaestus',
    nameRu: 'Промышленное поселение',
    nameEn: 'Industrial Settlement',
    group: 'Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 4,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 3, tech: 0, sol: 0, dev: 0 },
    haulTons: 36829,
    cargo: {
      aluminium: 7047,
      buildingfabricators: 407,
      ceramiccomposites: 814,
      cmmcomposite: 6776,
      computercomponents: 102,
      copper: 407,
      emergencypowercells: 68,
      evacuationshelter: 204,
      foodcartridges: 136,
      fruitandvegetables: 95,
      liquidoxygen: 2372,
      medicaldiagnosticequipment: 48,
      nonlethalweapons: 34,
      polymers: 678,
      powergenerators: 68,
      semiconductors: 102,
      steel: 10164,
      structuralregulators: 678,
      superconductors: 136,
      surfacestabilisers: 610,
      survivalequipment: 55,
      terrainenrichmentsystems: 68,
      titanium: 5760,
    },
  },
  {
    id: 'necessitas',
    nameRu: 'Научное поселение',
    nameEn: 'Scientific Settlement',
    group: 'Outpost',
    buildClass: 'outpost',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 4,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 0, tech: 5, sol: 0, dev: 1 },
    haulTons: 36829,
    cargo: {
      aluminium: 7047,
      buildingfabricators: 407,
      ceramiccomposites: 814,
      cmmcomposite: 6776,
      computercomponents: 102,
      copper: 407,
      emergencypowercells: 68,
      evacuationshelter: 204,
      foodcartridges: 136,
      fruitandvegetables: 95,
      liquidoxygen: 2372,
      medicaldiagnosticequipment: 48,
      nonlethalweapons: 34,
      polymers: 678,
      powergenerators: 68,
      semiconductors: 102,
      steel: 10164,
      structuralregulators: 678,
      superconductors: 136,
      surfacestabilisers: 610,
      survivalequipment: 55,
      terrainenrichmentsystems: 68,
      titanium: 5760,
    },
  },
  {
    id: 'zeus',
    nameRu: 'Планетарный порт',
    nameEn: 'Port Surface Outpost',
    group: 'Port',
    buildClass: 'starport',
    tier: 3,
    location: 'surface',
    pad: 'large',
    needs: { tier: 3, count: 6 },
    gives: { tier: 0, count: 0 },
    score: 15,
    influence: 'colony',
    effects: { pop: 10, mpop: 10, sec: -3, wealth: 5, tech: 5, sol: 7, dev: 10 },
    haulTons: 216030,
    cargo: {
      aluminium: 42282,
      buildingfabricators: 2442,
      ceramiccomposites: 4884,
      cmmcomposite: 40656,
      computercomponents: 408,
      copper: 2442,
      emergencypowercells: 272,
      evacuationshelter: 816,
      foodcartridges: 544,
      fruitandvegetables: 380,
      liquidoxygen: 14232,
      medicaldiagnosticequipment: 192,
      nonlethalweapons: 136,
      polymers: 2712,
      powergenerators: 272,
      semiconductors: 408,
      steel: 60984,
      structuralregulators: 2712,
      superconductors: 544,
      surfacestabilisers: 3660,
      survivalequipment: 220,
      terrainenrichmentsystems: 272,
      titanium: 34560,
    },
  },
  {
    id: 'consus',
    nameRu: 'Сельхозпоселение (малое)',
    nameEn: 'Agricultural Settlement - Small',
    group: 'Agriculture Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'small',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 1,
    influence: 'agriculture',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 0, sol: 3, dev: 0 },
    haulTons: 2839,
    cargo: {
      aluminium: 559,
      biowaste: 280,
      buildingfabricators: 42,
      ceramiccomposites: 28,
      computercomponents: 14,
      copper: 21,
      cropharvesters: 210,
      emergencypowercells: 84,
      evacuationshelter: 14,
      foodcartridges: 42,
      fruitandvegetables: 63,
      grain: 77,
      liquidoxygen: 224,
      pesticides: 126,
      polymers: 91,
      steel: 768,
      structuralregulators: 56,
      surfacestabilisers: 56,
      survivalequipment: 14,
      terrainenrichmentsystems: 70,
    },
  },
  {
    id: 'picumnus',
    nameRu: 'Сельхозпоселение (среднее)',
    nameEn: 'Agricultural Settlement - Medium',
    group: 'Agriculture Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'agriculture',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 0, sol: 7, dev: 0 },
    haulTons: 5678,
    cargo: {
      aluminium: 1118,
      biowaste: 560,
      buildingfabricators: 84,
      ceramiccomposites: 56,
      computercomponents: 28,
      copper: 42,
      cropharvesters: 420,
      emergencypowercells: 168,
      evacuationshelter: 28,
      foodcartridges: 84,
      fruitandvegetables: 126,
      grain: 154,
      liquidoxygen: 448,
      pesticides: 252,
      polymers: 182,
      steel: 1536,
      structuralregulators: 112,
      surfacestabilisers: 112,
      survivalequipment: 28,
      terrainenrichmentsystems: 140,
    },
  },
  {
    id: 'ceres',
    nameRu: 'Сельхозпоселение (большое)',
    nameEn: 'Agricultural Settlement - Large',
    group: 'Agriculture Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    score: 4,
    influence: 'agriculture',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 0, sol: 10, dev: 0 },
    haulTons: 8517,
    cargo: {
      aluminium: 1677,
      biowaste: 840,
      buildingfabricators: 126,
      ceramiccomposites: 84,
      computercomponents: 42,
      copper: 63,
      cropharvesters: 630,
      emergencypowercells: 252,
      evacuationshelter: 42,
      foodcartridges: 126,
      fruitandvegetables: 189,
      grain: 231,
      liquidoxygen: 672,
      pesticides: 378,
      polymers: 273,
      steel: 2304,
      structuralregulators: 168,
      surfacestabilisers: 168,
      survivalequipment: 42,
      terrainenrichmentsystems: 210,
    },
  },
  {
    id: 'ourea',
    nameRu: 'Добывающее поселение (малое)',
    nameEn: 'Extraction Settlement - Small',
    group: 'Extraction Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'small',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 1,
    influence: 'extraction',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 3, tech: 0, sol: 0, dev: 0 },
    haulTons: 2845,
    cargo: {
      aluminium: 632,
      bioreducinglichen: 162,
      buildingfabricators: 59,
      ceramiccomposites: 59,
      computercomponents: 30,
      copper: 30,
      emergencypowercells: 96,
      evacuationshelter: 30,
      foodcartridges: 45,
      fruitandvegetables: 30,
      geologicalequipment: 52,
      hazardousenvironmentsuits: 15,
      liquidoxygen: 177,
      mutomimager: 45,
      polymers: 118,
      robotics: 59,
      steel: 1028,
      structuralregulators: 74,
      surfacestabilisers: 89,
      survivalequipment: 15,
    },
  },
  {
    id: 'mantus',
    nameRu: 'Добывающее поселение (среднее)',
    nameEn: 'Extraction Settlement - Medium',
    group: 'Extraction Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'extraction',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 5, tech: 0, sol: 0, dev: 0 },
    haulTons: 5690,
    cargo: {
      aluminium: 1264,
      bioreducinglichen: 324,
      buildingfabricators: 118,
      ceramiccomposites: 118,
      computercomponents: 60,
      copper: 60,
      emergencypowercells: 192,
      evacuationshelter: 60,
      foodcartridges: 90,
      fruitandvegetables: 60,
      geologicalequipment: 104,
      hazardousenvironmentsuits: 30,
      liquidoxygen: 354,
      mutomimager: 90,
      polymers: 236,
      robotics: 118,
      steel: 2056,
      structuralregulators: 148,
      surfacestabilisers: 178,
      survivalequipment: 30,
    },
  },
  {
    id: 'erebus',
    nameRu: 'Добывающее поселение (большое)',
    nameEn: 'Extraction Settlement - Large',
    group: 'Extraction Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    score: 4,
    influence: 'extraction',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 8, tech: 2, sol: -2, dev: 0 },
    haulTons: 8535,
    cargo: {
      aluminium: 1896,
      bioreducinglichen: 486,
      buildingfabricators: 177,
      ceramiccomposites: 177,
      computercomponents: 90,
      copper: 90,
      emergencypowercells: 288,
      evacuationshelter: 90,
      foodcartridges: 135,
      fruitandvegetables: 90,
      geologicalequipment: 156,
      hazardousenvironmentsuits: 45,
      liquidoxygen: 531,
      mutomimager: 135,
      polymers: 354,
      robotics: 177,
      steel: 3084,
      structuralregulators: 222,
      surfacestabilisers: 267,
      survivalequipment: 45,
    },
  },
  {
    id: 'fontus',
    nameRu: 'Индустриальное поселение (малое)',
    nameEn: 'Industrial Settlement - Small',
    group: 'Industrial Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'small',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 1,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 0, sol: 0, dev: 3 },
    haulTons: 2845,
    cargo: {
      advancedcatalysers: 41,
      aluminium: 585,
      buildingfabricators: 55,
      ceramiccomposites: 55,
      computercomponents: 28,
      copper: 28,
      emergencypowercells: 28,
      evacuationshelter: 21,
      foodcartridges: 41,
      fruitandvegetables: 28,
      hazardousenvironmentsuits: 14,
      heliostaticfurnaces: 82,
      liquidoxygen: 272,
      microcontrollers: 14,
      mineralextractors: 164,
      polymers: 109,
      resonatingseparators: 14,
      robotics: 55,
      semiconductors: 14,
      steel: 1019,
      structuralregulators: 68,
      superconductors: 14,
      surfacestabilisers: 68,
      survivalequipment: 14,
      thermalcoolingunits: 14,
    },
  },
  {
    id: 'meteope',
    nameRu: 'Индустриальное поселение (среднее)',
    nameEn: 'Industrial Settlement - Medium',
    group: 'Industrial Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'large',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 0, sol: 0, dev: 6 },
    haulTons: 5690,
    cargo: {
      advancedcatalysers: 82,
      aluminium: 1170,
      buildingfabricators: 110,
      ceramiccomposites: 110,
      computercomponents: 56,
      copper: 56,
      emergencypowercells: 56,
      evacuationshelter: 42,
      foodcartridges: 82,
      fruitandvegetables: 56,
      hazardousenvironmentsuits: 28,
      heliostaticfurnaces: 164,
      liquidoxygen: 544,
      microcontrollers: 28,
      mineralextractors: 328,
      polymers: 218,
      resonatingseparators: 28,
      robotics: 110,
      semiconductors: 28,
      steel: 2038,
      structuralregulators: 136,
      superconductors: 28,
      surfacestabilisers: 136,
      survivalequipment: 28,
      thermalcoolingunits: 28,
    },
  },
  {
    id: 'gaea',
    nameRu: 'Индустриальное поселение (большое)',
    nameEn: 'Industrial Settlement - Large',
    group: 'Industrial Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    score: 4,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 3, tech: 0, sol: 0, dev: 9 },
    haulTons: 8535,
    cargo: {
      advancedcatalysers: 123,
      aluminium: 1755,
      buildingfabricators: 165,
      ceramiccomposites: 165,
      computercomponents: 84,
      copper: 84,
      emergencypowercells: 84,
      evacuationshelter: 63,
      foodcartridges: 123,
      fruitandvegetables: 84,
      hazardousenvironmentsuits: 42,
      heliostaticfurnaces: 246,
      liquidoxygen: 816,
      microcontrollers: 42,
      mineralextractors: 492,
      polymers: 327,
      resonatingseparators: 42,
      robotics: 165,
      semiconductors: 42,
      steel: 3057,
      structuralregulators: 204,
      superconductors: 42,
      surfacestabilisers: 204,
      survivalequipment: 42,
      thermalcoolingunits: 42,
    },
  },
  {
    id: 'ioke',
    nameRu: 'Военное поселение (малое)',
    nameEn: 'Military Settlement - Small',
    group: 'Military Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 1,
    influence: 'military',
    effects: { pop: 1, mpop: 1, sec: 2, wealth: 0, tech: 0, sol: 0, dev: 0 },
    haulTons: 2842,
    cargo: {
      aluminium: 593,
      basicmedicines: 36,
      battleweapons: 24,
      buildingfabricators: 60,
      ceramiccomposites: 60,
      cmmcomposite: 356,
      combatstabilisers: 36,
      computercomponents: 42,
      copper: 30,
      emergencypowercells: 24,
      evacuationshelter: 36,
      foodcartridges: 36,
      fruitandvegetables: 24,
      liquidoxygen: 172,
      microcontrollers: 12,
      militarygradefabrics: 24,
      polymers: 119,
      reactivearmour: 24,
      steel: 949,
      structuralregulators: 101,
      surfacestabilisers: 60,
      survivalequipment: 24,
    },
  },
  {
    id: 'bellona',
    nameRu: 'Военное поселение (среднее)',
    nameEn: 'Military Settlement - Medium',
    group: 'Military Tier 1',
    buildClass: 'settlement',
    tier: 1,
    location: 'surface',
    pad: 'medium',
    needs: { tier: 0, count: 0 },
    gives: { tier: 2, count: 1 },
    score: 2,
    influence: 'military',
    effects: { pop: 1, mpop: 1, sec: 4, wealth: 0, tech: 0, sol: 0, dev: 0 },
    haulTons: 5684,
    cargo: {
      aluminium: 1186,
      basicmedicines: 72,
      battleweapons: 48,
      buildingfabricators: 120,
      ceramiccomposites: 120,
      cmmcomposite: 712,
      combatstabilisers: 72,
      computercomponents: 84,
      copper: 60,
      emergencypowercells: 48,
      evacuationshelter: 72,
      foodcartridges: 72,
      fruitandvegetables: 48,
      liquidoxygen: 344,
      microcontrollers: 24,
      militarygradefabrics: 48,
      polymers: 238,
      reactivearmour: 48,
      steel: 1898,
      structuralregulators: 202,
      surfacestabilisers: 120,
      survivalequipment: 48,
    },
  },
  {
    id: 'minerva',
    nameRu: 'Военное поселение (большое)',
    nameEn: 'Military Settlement - Large',
    group: 'Military Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    score: 4,
    influence: 'military',
    effects: { pop: 1, mpop: 1, sec: 7, wealth: 0, tech: 0, sol: 0, dev: 3 },
    haulTons: 8526,
    cargo: {
      aluminium: 1779,
      basicmedicines: 108,
      battleweapons: 72,
      buildingfabricators: 180,
      ceramiccomposites: 180,
      cmmcomposite: 1068,
      combatstabilisers: 108,
      computercomponents: 126,
      copper: 90,
      emergencypowercells: 72,
      evacuationshelter: 108,
      foodcartridges: 108,
      fruitandvegetables: 72,
      liquidoxygen: 516,
      microcontrollers: 36,
      militarygradefabrics: 72,
      polymers: 357,
      reactivearmour: 72,
      steel: 2847,
      structuralregulators: 303,
      surfacestabilisers: 180,
      survivalequipment: 72,
    },
  },
  {
    id: 'pheobe',
    nameRu: 'Хайтек-поселение (малое)',
    nameEn: 'High Tech Settlement - Small',
    group: 'Research Bio Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'small',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 2,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 3, sol: 0, dev: 1 },
    haulTons: 2841,
    cargo: {
      advancedcatalysers: 95,
      aluminium: 607,
      basicmedicines: 14,
      buildingfabricators: 54,
      ceramiccomposites: 41,
      computercomponents: 41,
      copper: 34,
      emergencypowercells: 27,
      evacuationshelter: 27,
      foodcartridges: 41,
      fruitandvegetables: 27,
      geologicalequipment: 27,
      hazardousenvironmentsuits: 27,
      liquidoxygen: 351,
      medicaldiagnosticequipment: 41,
      microcontrollers: 14,
      mutomimager: 95,
      polymers: 115,
      semiconductors: 21,
      steel: 945,
      structuralregulators: 81,
      superconductors: 21,
      surfacestabilisers: 81,
      survivalequipment: 14,
    },
  },
  {
    id: 'asteria',
    nameRu: 'Хайтек-поселение (среднее)',
    nameEn: 'High Tech Settlement - Medium',
    group: 'Research Bio Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'small',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 2,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 7, sol: 0, dev: 1 },
    haulTons: 5682,
    cargo: {
      advancedcatalysers: 190,
      aluminium: 1214,
      basicmedicines: 28,
      buildingfabricators: 108,
      ceramiccomposites: 82,
      computercomponents: 82,
      copper: 68,
      emergencypowercells: 54,
      evacuationshelter: 54,
      foodcartridges: 82,
      fruitandvegetables: 54,
      geologicalequipment: 54,
      hazardousenvironmentsuits: 54,
      liquidoxygen: 702,
      medicaldiagnosticequipment: 82,
      microcontrollers: 28,
      mutomimager: 190,
      polymers: 230,
      semiconductors: 42,
      steel: 1890,
      structuralregulators: 162,
      superconductors: 42,
      surfacestabilisers: 162,
      survivalequipment: 28,
    },
  },
  {
    id: 'chronos',
    nameRu: 'Хайтек-поселение (большое)',
    nameEn: 'High Tech Settlement - Large',
    group: 'Research Bio Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    score: 4,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 10, sol: 0, dev: 3 },
    haulTons: 8523,
    cargo: {
      advancedcatalysers: 285,
      aluminium: 1821,
      basicmedicines: 42,
      buildingfabricators: 162,
      ceramiccomposites: 123,
      computercomponents: 123,
      copper: 102,
      emergencypowercells: 81,
      evacuationshelter: 81,
      foodcartridges: 123,
      fruitandvegetables: 81,
      geologicalequipment: 81,
      hazardousenvironmentsuits: 81,
      liquidoxygen: 1053,
      medicaldiagnosticequipment: 123,
      microcontrollers: 42,
      mutomimager: 285,
      polymers: 345,
      semiconductors: 63,
      steel: 2835,
      structuralregulators: 243,
      superconductors: 63,
      surfacestabilisers: 243,
      survivalequipment: 42,
    },
  },
  {
    id: 'aergia',
    nameRu: 'Турпоселение (малое)',
    nameEn: 'Tourism Settlement - Small',
    group: 'Tourism Tier 1',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'medium',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'satellite',
    score: 1,
    influence: 'tourism',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 1, tech: 0, sol: 0, dev: 0 },
    haulTons: 2846,
    cargo: {
      aluminium: 509,
      animalmeat: 71,
      beer: 311,
      buildingfabricators: 29,
      ceramiccomposites: 43,
      coffee: 71,
      computercomponents: 15,
      copper: 22,
      emergencypowercells: 15,
      evacuationshelter: 22,
      fish: 36,
      fruitandvegetables: 71,
      liquidoxygen: 227,
      liquor: 128,
      polymers: 114,
      steel: 707,
      structuralregulators: 57,
      surfacestabilisers: 57,
      survivalequipment: 15,
      tea: 170,
      wine: 156,
    },
  },
  {
    id: 'comus',
    nameRu: 'Турпоселение (среднее)',
    nameEn: 'Tourism Settlement - Medium',
    group: 'Tourism Tier 1',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'satellite',
    score: 2,
    influence: 'tourism',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 3, tech: 0, sol: 0, dev: 0 },
    haulTons: 5692,
    cargo: {
      aluminium: 1018,
      animalmeat: 142,
      beer: 622,
      buildingfabricators: 58,
      ceramiccomposites: 86,
      coffee: 142,
      computercomponents: 30,
      copper: 44,
      emergencypowercells: 30,
      evacuationshelter: 44,
      fish: 72,
      fruitandvegetables: 142,
      liquidoxygen: 454,
      liquor: 256,
      polymers: 228,
      steel: 1414,
      structuralregulators: 114,
      surfacestabilisers: 114,
      survivalequipment: 30,
      tea: 340,
      wine: 312,
    },
  },
  {
    id: 'fufluns',
    nameRu: 'Турпоселение (большое)',
    nameEn: 'Tourism Settlement - Large',
    group: 'Tourism Tier 2',
    buildClass: 'settlement',
    tier: 2,
    location: 'surface',
    pad: 'large',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 2 },
    preReq: 'satellite',
    score: 4,
    influence: 'tourism',
    effects: { pop: 1, mpop: 1, sec: -2, wealth: 5, tech: 0, sol: 0, dev: 0 },
    haulTons: 8538,
    cargo: {
      aluminium: 1527,
      animalmeat: 213,
      beer: 933,
      buildingfabricators: 87,
      ceramiccomposites: 129,
      coffee: 213,
      computercomponents: 45,
      copper: 66,
      emergencypowercells: 45,
      evacuationshelter: 66,
      fish: 108,
      fruitandvegetables: 213,
      liquidoxygen: 681,
      liquor: 384,
      polymers: 342,
      steel: 2121,
      structuralregulators: 171,
      surfacestabilisers: 171,
      survivalequipment: 45,
      tea: 510,
      wine: 468,
    },
  },
  {
    id: 'tartarus',
    nameRu: 'Добывающий хаб',
    nameEn: 'Extraction Hub',
    group: 'Extraction',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'settlementExtraction',
    score: 5,
    influence: 'extraction',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 10, tech: 0, sol: -4, dev: 3 },
    haulTons: 9919,
    cargo: {
      aluminium: 2352,
      bioreducinglichen: 714,
      buildingfabricators: 210,
      ceramiccomposites: 252,
      computercomponents: 38,
      copper: 84,
      emergencypowercells: 42,
      evacuationshelter: 51,
      foodcartridges: 51,
      fruitandvegetables: 34,
      geologicalequipment: 210,
      hazardousenvironmentsuits: 126,
      mutomimager: 160,
      polymers: 672,
      powergenerators: 26,
      robotics: 252,
      steel: 3359,
      structuralregulators: 504,
      surfacestabilisers: 756,
      survivalequipment: 26,
    },
  },
  {
    id: 'aegle',
    nameRu: 'Гражданский хаб',
    nameEn: 'Civilian Hub',
    group: 'Civilian',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'settlementAgr',
    score: 5,
    influence: 'none',
    effects: { pop: 1, mpop: 1, sec: -3, wealth: 0, tech: 0, sol: 3, dev: 3 },
    haulTons: 9924,
    cargo: {
      agriculturalmedicines: 235,
      aluminium: 2433,
      biowaste: 630,
      buildingfabricators: 84,
      ceramiccomposites: 126,
      computercomponents: 21,
      copper: 68,
      cropharvesters: 210,
      emergencypowercells: 42,
      evacuationshelter: 68,
      foodcartridges: 68,
      fruitandvegetables: 42,
      pesticides: 378,
      polymers: 630,
      powergenerators: 26,
      steel: 3775,
      structuralregulators: 336,
      surfacestabilisers: 588,
      survivalequipment: 38,
      terrainenrichmentsystems: 126,
    },
  },
  {
    id: 'tellus',
    nameRu: 'Исследовательский хаб',
    nameEn: 'Exploration Hub',
    group: 'Exploration',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'comms',
    score: 5,
    influence: 'tourism',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 0, tech: 7, sol: 0, dev: 3 },
    haulTons: 9923,
    cargo: {
      aluminium: 2483,
      buildingfabricators: 89,
      ceramiccomposites: 134,
      computercomponents: 49,
      copper: 178,
      emergencypowercells: 45,
      evacuationshelter: 36,
      foodcartridges: 54,
      fruitandvegetables: 36,
      geologicalequipment: 621,
      hazardousenvironmentsuits: 249,
      polymers: 666,
      powergenerators: 32,
      steel: 3547,
      structuralregulators: 267,
      surfacestabilisers: 1419,
      survivalequipment: 18,
    },
  },
  {
    id: 'io',
    nameRu: 'Аванпост-хаб',
    nameEn: 'Outpost Hub',
    group: 'Outpost',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'installationAgr',
    score: 5,
    influence: 'none',
    effects: { pop: 1, mpop: 1, sec: -2, wealth: 0, tech: 0, sol: 3, dev: 3 },
    haulTons: 9922,
    cargo: {
      aluminium: 2797,
      buildingfabricators: 290,
      ceramiccomposites: 145,
      computercomponents: 25,
      copper: 78,
      emergencypowercells: 49,
      evacuationshelter: 49,
      foodcartridges: 174,
      fruitandvegetables: 87,
      polymers: 724,
      powergenerators: 25,
      steel: 4051,
      structuralregulators: 338,
      surfacestabilisers: 1061,
      survivalequipment: 29,
    },
  },
  {
    id: 'athena',
    nameRu: 'Научный хаб',
    nameEn: 'Scientific Hub',
    group: 'Scientific',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 5,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 0, tech: 10, sol: 0, dev: 0 },
    haulTons: 9924,
    cargo: {
      advancedcatalysers: 170,
      aluminium: 2581,
      basicmedicines: 72,
      buildingfabricators: 178,
      ceramiccomposites: 223,
      computercomponents: 67,
      copper: 112,
      emergencypowercells: 63,
      evacuationshelter: 36,
      foodcartridges: 54,
      fruitandvegetables: 36,
      geologicalequipment: 401,
      hazardousenvironmentsuits: 156,
      medicaldiagnosticequipment: 161,
      microcontrollers: 49,
      mutomimager: 107,
      polymers: 712,
      powergenerators: 36,
      semiconductors: 72,
      steel: 3560,
      structuralregulators: 445,
      superconductors: 72,
      surfacestabilisers: 534,
      survivalequipment: 27,
    },
  },
  {
    id: 'alala',
    nameRu: 'Военный хаб',
    nameEn: 'Military Hub',
    group: 'Military',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'installationMil',
    score: 5,
    influence: 'military',
    effects: { pop: 1, mpop: 1, sec: 10, wealth: 0, tech: 0, sol: 0, dev: 0 },
    haulTons: 9922,
    cargo: {
      aluminium: 2414,
      basicmedicines: 109,
      battleweapons: 42,
      buildingfabricators: 333,
      ceramiccomposites: 375,
      cmmcomposite: 333,
      combatstabilisers: 25,
      computercomponents: 75,
      copper: 105,
      emergencypowercells: 63,
      evacuationshelter: 75,
      foodcartridges: 125,
      fruitandvegetables: 42,
      microcontrollers: 55,
      militarygradefabrics: 42,
      polymers: 708,
      powergenerators: 38,
      reactivearmour: 42,
      steel: 3746,
      structuralregulators: 542,
      surfacestabilisers: 583,
      survivalequipment: 50,
    },
  },
  {
    id: 'silenus',
    nameRu: 'Перерабатывающий хаб',
    nameEn: 'Refinery Hub',
    group: 'Refinery',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 5,
    influence: 'refinery',
    effects: { pop: 1, mpop: 1, sec: -1, wealth: 5, tech: 3, sol: -2, dev: 7 },
    haulTons: 9919,
    cargo: {
      advancedcatalysers: 112,
      aluminium: 2697,
      buildingfabricators: 233,
      ceramiccomposites: 279,
      computercomponents: 42,
      copper: 93,
      emergencypowercells: 47,
      evacuationshelter: 56,
      foodcartridges: 56,
      fruitandvegetables: 38,
      hazardousenvironmentsuits: 117,
      polymers: 744,
      powergenerators: 28,
      resonatingseparators: 84,
      robotics: 419,
      steel: 3720,
      structuralregulators: 465,
      surfacestabilisers: 558,
      survivalequipment: 28,
      thermalcoolingunits: 103,
    },
  },
  {
    id: 'janus',
    nameRu: 'Хайтек-хаб',
    nameEn: 'High Tech Hub',
    group: 'High Tech',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    score: 5,
    influence: 'hightech',
    effects: { pop: 1, mpop: 1, sec: -2, wealth: 3, tech: 10, sol: 0, dev: 0 },
    haulTons: 9921,
    cargo: {
      aluminium: 2512,
      buildingfabricators: 135,
      ceramiccomposites: 225,
      cmmcomposite: 270,
      computercomponents: 68,
      copper: 113,
      emergencypowercells: 59,
      evacuationshelter: 45,
      foodcartridges: 54,
      fruitandvegetables: 36,
      microcontrollers: 90,
      polymers: 673,
      powergenerators: 27,
      robotics: 449,
      semiconductors: 108,
      steel: 3768,
      structuralregulators: 404,
      superconductors: 108,
      surfacestabilisers: 539,
      survivalequipment: 27,
      thermalcoolingunits: 211,
    },
  },
  {
    id: 'molae',
    nameRu: 'Индустриальный хаб',
    nameEn: 'Industrial Hub',
    group: 'Industrial',
    buildClass: 'hub',
    tier: 2,
    location: 'surface',
    pad: 'none',
    needs: { tier: 2, count: 1 },
    gives: { tier: 3, count: 1 },
    preReq: 'outpostMining',
    score: 5,
    influence: 'industrial',
    effects: { pop: 1, mpop: 1, sec: 0, wealth: 5, tech: 3, sol: -4, dev: 3 },
    haulTons: 9919,
    cargo: {
      aluminium: 2407,
      buildingfabricators: 208,
      ceramiccomposites: 249,
      cmmcomposite: 166,
      computercomponents: 38,
      copper: 83,
      emergencypowercells: 42,
      evacuationshelter: 50,
      foodcartridges: 50,
      fruitandvegetables: 34,
      hazardousenvironmentsuits: 83,
      heliostaticfurnaces: 415,
      microcontrollers: 50,
      mineralextractors: 415,
      polymers: 664,
      powergenerators: 25,
      robotics: 332,
      semiconductors: 75,
      steel: 3320,
      structuralregulators: 498,
      superconductors: 75,
      surfacestabilisers: 498,
      survivalequipment: 25,
      thermalcoolingunits: 117,
    },
  },
];
